spring.application.name=HavenGlam

/* por favor cambiar a su contraseña de Mysql*/
#Acceso a la base de datos
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/havenglam_db?userSSl=true
spring.datasource.username=root
spring.datasource.password=Nina2026/

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Estrategia de nombrado para mantener nombres exactos definidos en @Table y @Column (sin guiones bajos)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect